--Day 16

CREATE DATABASE PixelTech;

USE PixelTech;

CREATE TABLE Student
(
	StudentID INT NOT NULL IDENTITY(1,1),
	StudentName VARCHAR(20)
);
DROP TABLE Student;

ALTER TABLE Student
ADD CONSTRAINT PKStudentID PRIMARY KEY(StudentID);

ALTER TABLE Student
ALTER COLUMN StudentName VARCHAR(20) NOT NULL;


INSERT INTO Student (StudentName) values('Swapnil'),
('ABC'),('PQR'),('XYZ'),('IJK')

SELECT * FROM Student;

delete from Student where StudentID=2;

SET IDENTITY_INSERT Student ON;--ENABLES INSERTING OUR OWN CUSTOMIZED ID

INSERT INTO Student(StudentID ,StudentName) VALUES(2, 'ABC');

SET IDENTITY_INSERT Student OFF;

CREATE TABLE Library
(
	BookID VARCHAR(20) NOT NULL,
	BookName VARCHAR(20) NOT NULL,
	StudentID INT NOT NULL,
	IssueDate DATE CONSTRAINT DDate DEFAULT GETDATE(),
	ReturnDays INT CONSTRAINT CheckReturnDays Check(ReturnDays<=14)
)

ALTER TABLE Library
ADD FOREIGN KEY (StudentID) REFERENCES Student(StudentID);

INSERT INTO Library(BookID ,BookName, StudentID, IssueDate, ReturnDays) VALUES(1, 'SQL', 2, DEFAULT, 0);

INSERT INTO Library(BookID ,BookName, StudentID, IssueDate, ReturnDays) VALUES(2, '.NET', 4, DEFAULT, 0);

SELECT * FROM Library;

UPDATE Library
SET ReturnDays = 15;--WE'VE SET CHECK CONSTRAINT ON RETURNS DAYS SO IT WONT VALUES GREATER THAN 14

UPDATE Library
SET ReturnDays = 14;--CHECK CONSTRAINT WILL ALLOW 14 BECAUSE IT MEETS THE CONDITION MENTIONED IN CHECK CONSTRAINT

UPDATE Library
SET ReturnDays = 7
WHERE BookID = 2;

ALTER TABLE Library
ADD ReturnDate DATE CONSTRAINT DefaultReturnDate DEFAULT GETDATE()+7

INSERT INTO Library(BookID ,BookName, StudentID, IssueDate, ReturnDays) VALUES(3, '.NET', 3, DEFAULT, 0);

UPDATE Library
SET ReturnDate = DATEADD(DD,7,IssueDate)
Where BookID = 1;--UPDATING PREVIOUS RECORDS WHICH WERE NULL IE BEFORE APPLYING DEFAULT CONSTRAINT

UPDATE Library
SET ReturnDate = DATEADD(DD,9,IssueDate)
Where BookID = 2;

ALTER TABLE Library
DROP COLUMN ReturnDays;--THIS COLUMN IS DEPENDENT ON CONSTRAINT SO WE WONT BE ABLE TO DROP

--SO WE NEED TO DROP THAT CONSTRAINT FIRST
ALTER TABLE Library
DROP CONSTRAINT CheckReturnDays;

--CONSTRAINT ATTACHED TO ReturnDays IS DROPPED SO NOW WE ARE FREE TO DROP THE TABLE
ALTER TABLE Library
DROP COLUMN ReturnDays;--SO AGIN WE EXECUTED THIS QUERY & GENERATED NO EXCEPTION

SP_RENAME 'Library.IssueDate','DateIssued', 'column';--RENAMES THE SPECIFIED COLUMN
--COLUMN WHICH WE WANT TO RENAME MUST BE SPECIFIED WITH TABLE NAME
SELECT * FROM Library;

SP_RENAME 'Library', 'CrossWorld'--RENAMING TABLE USING STORED PROCEDURE

SELECT * FROM CrossWorld;

SP_RENAMEdb 'PixelTech', 'PixelThink'

SP_HELP --HELPS TO SEE THE CONTENTS OF TABLE

SP_HELP Student --LISTS ALL THE OBJECTS PRESENT IN THAT PERTICULAR TABLE

SP_HELPDB PixelThink  -- LELPS TO SEE THE CONTENTS OF DB